map_popular = {
    'Unpopular': 0, 
    'Popular': 1
}

map_reverse_popular = {
    1: 'popular',
    0: 'unpopular'
}

map_genres = {
    '44 scotland street (edinburgh, scotland : imaginary place)': ('Literature & Fiction','Fiction'),
    'abused children': ('Non-Fiction', 'Family & Relationships'),
    'acting': ('Arts & Entertainment', 'Performing Arts'),
    'actresses': ('Non-Fiction', 'Biography & Memoir'),
    'adjoining landowners': ('Non-Fiction', 'Law & Politics'),
    'adobe acrobat': ('Non-Fiction', 'Technology & Engineering'),
    'adoptees': ('Non-Fiction', 'Family & Relationships'),
    'adultery': ('Literature & Fiction', 'Fiction'),
    'adventure': ('Literature & Fiction', 'Adventure'),
    'afghanistan': ('Travel & Adventure', 'Destination'),
    'africa, sub-saharan': ('Travel & Adventure', 'Destination'),
    'african american civil rights workers': ('Non-Fiction', 'History'),
    'african american journalists': ('Non-Fiction', 'History'),
    'african americans': ('Non-Fiction', 'History'),
    'agape': ('Non-Fiction', 'Religion & Spirituality'),
    'agriculture': ('Non-Fiction', 'Science & Nature'),
    'alcoholic beverages': ('Lifestyle & Home', 'Cooking'),
    'algebra': ('Non-Fiction', 'Science & Nature'),
    'american fiction': ('Literature & Fiction', 'Fiction'),
    'anger': ('Non-Fiction', 'Self-Help & Psychology'),
    'animals': ('Non-Fiction', 'Science & Nature'),
    'anthroposophy': ('Non-Fiction', 'Religion & Spirituality'),
    'antiques & collectibles': ('Lifestyle & Home', 'Home & Garden'),
    'apologetics': ('Non-Fiction', 'Religion & Spirituality'),
    'apostles': ('Non-Fiction', 'Religion & Spirituality'),
    'architecture': ('Arts & Entertainment', 'Architecture'),
    'arctic regions': ('Travel & Adventure', 'Destination'),
    'arson': ('Literature & Fiction', 'Mystery & Crime'),
    'art': ('Arts & Entertainment', 'Visual Arts'),
    'art oratoire': ('Arts & Entertainment', 'Performing Arts'),
    'assisi (italy)': ('Travel & Adventure', 'Destination'),
    'asthma': ('Non-Fiction', 'Health & Fitness'),
    'astronauts': ('Non-Fiction', 'Biography & Memoir'),
    'athens (greece)': ('Travel & Adventure', 'Destination'),
    'attitude (psychology)': ('Non-Fiction', 'Self-Help & Psychology'),
    'audiobooks': ('Special Topics', 'Audiobooks'),
    'australia': ('Travel & Adventure', 'Destination'),
    'authorship': ('Non-Fiction', 'Authorship'),
    'autism': ('Non-Fiction', 'Health & Fitness'),
    'automobile mechanics': ('Special Topics', 'Hobbies & Interests'),
    'avarice': ('Non-Fiction', 'Self-Help & Psychology'),
    'avocado': ('Non-Fiction', 'Science & Nature'),
    'back bay (boston, mass.)': ('Travel & Adventure', 'Destination'),
    'bakersfield region (calif.)': ('Travel & Adventure', 'Destination'),
    'balsan, consuelo vanderbilt': ('Non-Fiction', 'Biography & Memoir'),
    'bands (music)': ('Arts & Entertainment', 'Music'),
    'baseball': ('Special Topics', 'Sports & Recreation'),
    'basil.': ('Literature & Fiction', 'Fiction'),
    'beauty, personal': ('Lifestyle & Home', 'Health & Wellness'),
    'behavior': ('Non-Fiction', 'Self-Help & Psychology'),
    'behavior disorders in children': ('Non-Fiction', 'Health & Fitness'),
    'best sellers': ('Literature & Fiction', 'Fiction'),
    'betterments': ('Non-Fiction', 'Self-Help & Psychology'),
    'bible': ('Non-Fiction', 'Religion & Spirituality'),
    'bibles': ('Non-Fiction', 'Religion & Spirituality'),
    'bilingual': ('Special Topics', 'Language & Linguistics'),
    'biography & autobiography': ('Non-Fiction', 'Biography & Memoir'),
    'bkaʼ-gdams-pa (sect)': ('Non-Fiction', 'Religion & Spirituality'),
    'board books': ("Children's & Young Adult", "Children's Fiction"),
    'body, mind & spirit': ('Non-Fiction', 'Self-Help & Psychology'),
    'bodybuilding': ('Lifestyle & Home', 'Health & Fitness'),
    'books and reading': ('Non-Fiction', 'Self-Help & Psychology'),
    'bosch, harry (fictitious character)': ('Literature & Fiction', 'Fiction'),
    'boxcar children (fictitous characters)': ("Children's & Young Adult", "Children's Fiction"),
    'boys': ("Children's & Young Adult", "Children's Fiction"),
    'brothers and sisters': ('Lifestyle & Home', 'Family & Relationships'),
    'bullies': ('Non-Fiction', 'Self-Help & Psychology'),
    'business & economics': ('Non-Fiction', 'Social Science'),
    'business cycles': ('Non-Fiction', 'Social Science'),
    'business forecasting': ('Non-Fiction', 'Business & Economics'),
    'business networks': ('Non-Fiction', 'Business & Economics'),
    'business planning': ('Non-Fiction', 'Business & Economics'),
    'cadfael, brother (fictitious character)': ('Literature & Fiction', 'Fiction'),
    'cake decorating': ('Lifestyle & Home', 'Cooking'),
    'camping': ('Travel & Adventure', 'Camping'),
    'canada': ('Travel & Adventure', 'Destination'),
    'captain underpants (fictitious character)': ('Literature & Fiction', 'Graphic Novels & Comics'),
    'carbohydrates, refined': ('Non-Fiction', 'Health & Fitness'),
    'carving (meat, etc.)': ('Lifestyle & Home', 'Cooking'),
    'casanova de seingalt, giacomo girolamo, 1725-1798': ('Non-Fiction', 'Biography & Memoir'),
    'case-based reasoning': ('Non-Fiction', 'Social Science'),
    'cats': ('Non-Fiction', 'Science & Nature'),
    'charity-schools': ('Literature & Fiction', 'Fiction'),
    'charlie (fictitious character : child)': ('Literature & Fiction', 'Fiction'),
    'chicago (ill.)': ('Travel & Adventure', 'Destination'),
    'child psychology': ('Non-Fiction', 'Education'),
    'child rearing': ('Lifestyle & Home', 'Family & Relationships'),
    'child welfare': ('Non-Fiction', 'Family & Relationships'),
    'children': ("Children's & Young Adult", "Children's Non-Fiction"),
    'children with disabilities': ('Non-Fiction', 'Family & Relationships'),
    'childrens encyclopedias and dictionaries': ("Children's & Young Adult", "Children's Non-Fiction"),
    'childrens poetry': ("Children's & Young Adult", 'Poetry'),
    'childrens poetry, english': ("Children's & Young Adult", 'Poetry'),
    'childrens stories': ("Children's & Young Adult", "Children's Fiction"),
    'christian life': ('Non-Fiction', 'Religion & Spirituality'),
    'christmas': ('Lifestyle & Home', 'Family & Relationships'),
    'church year meditations': ('Non-Fiction', 'Religion & Spirituality'),
    'clairvoyants': ('Special Topics', 'Fantasy & Paranormal'),
    'classical drama': ('Literature & Fiction', 'Drama'),
    'clothing and dress': ('Lifestyle & Home', 'Home & Garden'),
    'clouds': ('Non-Fiction', 'Science & Nature'),
    'codependency': ('Non-Fiction', 'Self-Help & Psychology'),
    'college student orientation': ('Non-Fiction', 'Education'),
    'colombia': ('Travel & Adventure', 'Destination'),
    'colombo (sri lanka)': ('Travel & Adventure', 'Destination'),
    'colors': ('Arts & Entertainment', 'Visual Arts'),
    'comic books, strips, etc': ('Literature & Fiction', 'Graphic Novels & Comics'),
    'comics & graphic novels': ('Literature & Fiction', 'Graphic Novels & Comics'),
    'comics & graphic novels.': ('Literature & Fiction', 'Graphic Novels & Comics'),
    'commercial correspondence': ('Non-Fiction', 'Business & Economics'),
    'commercial real estate': ('Non-Fiction', 'Business & Economics'),
    'communism': ('Non-Fiction', 'Social Science'),
    'composition (music)': ('Arts & Entertainment', 'Music'),
    'computer network protocols': ('Non-Fiction', 'Technology & Engineering'),
    'computers': ('Non-Fiction', 'Technology & Engineering'),
    'concentration camps': ('Non-Fiction', 'History'),
    'conduct of life': ('Non-Fiction', 'Self-Help & Psychology'),
    'conspiracies': ('Special Topics', 'Conspiracies'),
    'conversation': ('Non-Fiction', 'Self-Help & Psychology'),
    'cookery': ('Lifestyle & Home', 'Cooking'),
    'cooking': ('Lifestyle & Home', 'Cooking'),
    'cooking (spices)': ('Lifestyle & Home', 'Cooking'),
    'counterculture': ('Special Topics', 'Counterculture'),
    'counting': ("Children's & Young Adult", "Children's Non-Fiction"),
    'country homes': ('Lifestyle & Home', 'Home & Garden'),
    'country life': ('Lifestyle & Home', 'Home & Garden'),
    'courage': ('Non-Fiction', 'Self-Help & Psychology'),
    'courtroom artists': ('Arts & Entertainment', 'Visual Arts'),
    'crafts & hobbies': ('Arts & Entertainment', 'Crafts & Hobbies'),
    'crime': ('Literature & Fiction', 'Mystery & Crime'),
    'crimes without victims': ('Literature & Fiction', 'Mystery & Crime'),
    'crystals': ('Special Topics', 'Crystals'),
    'current events': ('Special Topics', 'Current Events'),
    'cycles': ('Special Topics', 'Cycles'),
    'czech fiction': ('Literature & Fiction', 'Fiction'),
    'dalziel, andrew (fictitious character)': ('Literature & Fiction', 'Fiction'),
    'death & dying': ('Non-Fiction', 'Self-Help & Psychology'),
    'decoration and ornament': ('Lifestyle & Home', 'Home & Garden'),
    'decorative arts': ('Arts & Entertainment', 'Visual Arts'),
    'denali national park and preserve (alaska)': ('Travel & Adventure', 'Destination'),
    'design': ('Arts & Entertainment', 'Visual Arts'),
    'desserts': ('Lifestyle & Home', 'Cooking'),
    'detective and mystery comic books, strips, etc': ('Literature & Fiction', 'Graphic Novels & Comics'),
    'detective and mystery stories': ('Literature & Fiction', 'Mystery & Crime'),
    'detective and mystery stories, american': ('Literature & Fiction', 'Mystery & Crime'),
    'detective and mystery stories, english': ('Literature & Fiction', 'Mystery & Crime'),
    'deverry (imaginary place)': ('Literature & Fiction', 'Fiction'),
    'diabetes': ('Non-Fiction', 'Health & Fitness'),
    'diaries': ('Non-Fiction', 'Biography & Memoir'),
    'dieu - amour': ('Non-Fiction', 'Religion & Spirituality'),
    'differential equations': ('Non-Fiction', 'Science & Nature'),
    'digital media': ('Special Topics', 'Technology & Engineering'),
    'diplomatic and consular service': ('Non-Fiction', 'Law & Politics'),
    'dogs': ('Non-Fiction', 'Science & Nature'),
    'domestic fiction': ('Literature & Fiction', 'Fiction'),
    'dominican republic': ('Travel & Adventure', 'Destination'),
    'drama': ('Literature & Fiction', 'Drama'),
    'dramatists, english': ('Literature & Fiction', 'Drama'),
    'economics': ('Non-Fiction', 'Social Science'),
    'education': ('Non-Fiction', 'Education'),
    'education, higher': ('Non-Fiction', 'Education'),
    'english fiction': ('Literature & Fiction', 'Drama'),
    'english language': ('Special Topics', 'Language & Linguistics'),
    'environmental protection': ('Non-Fiction', 'Science & Nature'),
    'executions and executioners': ('Non-Fiction', 'History'),
    'expectation (psychology)': ('Non-Fiction', 'Self-Help & Psychology'),
    'extraterrestrial beings': ('Special Topics', 'Fantasy & Paranormal'),
    'fairies': ('Special Topics', 'Fantasy & Paranormal'),
    'fairy tales': ("Children's & Young Adult", "Children's Fiction"),
    'faith': ('Non-Fiction', 'Religion & Spirituality'),
    'family & relationships': ('Lifestyle & Home', 'Family & Relationships'),
    'fantasy fiction': ('Literature & Fiction', 'Fiction'),
    'fiction': ('Literature & Fiction', 'Fiction'),
    'film posters, american': ('Arts & Entertainment', 'Visual Arts'),
    'finance, personal': ('Non-Fiction', 'Social Science'),
    'finance, public': ('Non-Fiction', 'Social Science'),
    'flags': ('Special Topics', 'Flags'),
    'food': ('Lifestyle & Home', 'Cooking'),
    'foreign language study': ('Special Topics', 'Language & Linguistics'),
    'fourth dimension': ('Special Topics', 'Science'),
    'french drama': ('Literature & Fiction', 'Drama'),
    'friendship': ('Non-Fiction', 'Self-Help & Psychology'),
    'fruit': ('Lifestyle & Home', 'Cooking'),
    'gambling systems': ('Special Topics', 'Hobbies & Interests'),
    'games': ('Special Topics', 'Hobbies & Interests'),
    'games & activities': ('Special Topics', 'Hobbies & Interests'),
    'gardening': ('Lifestyle & Home', 'Home & Garden'),
    'ghosts': ('Special Topics', 'Fantasy & Paranormal'),
    'gifts': ('Lifestyle & Home', 'Home & Garden'),
    'good and evil': ('Non-Fiction', 'Philosophy'),
    'greece': ('Travel & Adventure', 'Destination'),
    'hairdressing': ('Lifestyle & Home', 'Health & Wellness'),
    'hand-to-hand fighting': ('Non-Fiction', 'Sports & Recreation'),
    'handicraft': ('Arts & Entertainment', 'Crafts & Hobbies'),
    'hanukkah': ('Non-Fiction', 'Religion & Spirituality'),
    'health & fitness': ('Non-Fiction', 'Health & Fitness'),
    'hell': ('Non-Fiction', 'Religion & Spirituality'),
    'hindu hymns': ('Non-Fiction', 'Religion & Spirituality'),
    'hinduism': ('Non-Fiction', 'Religion & Spirituality'),
    'hippies': ('Special Topics', 'Counterculture'),
    'historical fiction': ('Literature & Fiction', 'Fiction'),
    'historical geography': ('Non-Fiction', 'History'),
    'history': ('Non-Fiction', 'History'),
    'hobo spider': ('Non-Fiction', 'Science & Nature'),
    'holocaust, jewish (1939-1945)': ('Non-Fiction', 'History'),
    'honesty': ('Non-Fiction', 'Self-Help & Psychology'),
    'hopi indians': ('Non-Fiction', 'History'),
    'horror films': ('Arts & Entertainment', 'Performing Arts'),
    'horses': ('Non-Fiction', 'Science & Nature'),
    'house & home': ('Lifestyle & Home', 'Home & Garden'),
    'housing': ('Lifestyle & Home', 'Home & Garden'),
    'humor': ('Special Topics', 'Humor'),
    'immigrants': ('Non-Fiction', 'Social Science'),
    'impressionism': ('Arts & Entertainment', 'Visual Arts'),
    'indiana': ('Travel & Adventure', 'Destination'),
    'indians of north america': ('Non-Fiction', 'History'),
    'insects': ('Non-Fiction', 'Science & Nature'),
    'insurance agents': ('Non-Fiction', 'Business & Economics'),
    'interior decoration': ('Lifestyle & Home', 'Home & Garden'),
    'invective': ('Special Topics', 'Invective'),
    'iso 9000 series standards': ('Non-Fiction', 'Business & Economics'),
    'israeli fiction': ('Literature & Fiction', 'Fiction'),
    'jacobites': ('Non-Fiction', 'History'),
    'jamaica': ('Travel & Adventure', 'Destination'),
    'japan': ('Travel & Adventure', 'Destination'),
    'juvenile fiction': ("Children's & Young Adult", "Children's Fiction"),
    'juvenile nonfiction': ("Children's & Young Adult", "Children's Non-Fiction"),
    'kung fu': ('Special Topics', 'Sports & Recreation'),
    'language and languages': ('Special Topics', 'Language & Linguistics'),
    'language arts & disciplines': ('Special Topics', 'Language & Linguistics'),
    'large type books': ('Special Topics', 'Large Type Books'),
    'law': ('Non-Fiction', 'Law & Politics'),
    'leadership': ('Non-Fiction', 'Business & Economics'),
    'lebanon': ('Travel & Adventure', 'Destination'),
    'leeward islands (west indies)': ('Travel & Adventure', 'Destination'),
    'lesbians': ('Non-Fiction', 'Social Science'),
    'literary collections': ('Literature & Fiction', 'Collections'),
    'literary criticism': ('Literature & Fiction', 'Criticism'),
    'love stories': ('Literature & Fiction', 'Fiction'),
    'mathematics': ('Non-Fiction', 'Science & Nature'),
    'meat': ('Lifestyle & Home', 'Cooking'),
    'medical': ('Non-Fiction', 'Health & Fitness'),
    'medicine, tibetan': ('Non-Fiction', 'Health & Fitness'),
    'memory': ('Non-Fiction', 'Self-Help & Psychology'),
    'mexican american tales': ('Literature & Fiction', 'Fiction'),
    'microsoft .net framework': ('Non-Fiction', 'Technology & Engineering'),
    'mormon church': ('Non-Fiction', 'Religion & Spirituality'),
    'mortars (ordnance)': ('Non-Fiction', 'Mortars'),
    'motherhood': ('Lifestyle & Home', 'Family & Relationships'),
    'motion pictures': ('Arts & Entertainment', 'Performing Arts'),
    'mushrooms': ('Non-Fiction', 'Science & Nature'),
    'music': ('Arts & Entertainment', 'Music'),
    'mystery.': ('Literature & Fiction', 'Mystery & Crime'),
    'nature': ('Non-Fiction', 'Science & Nature'),
    'note-taking': ('Special Topics', 'Reference'),
    'nutrition': ('Non-Fiction', 'Health & Fitness'),
    'organizational behavior': ('Non-Fiction', 'Business & Economics'),
    'organizational change': ('Non-Fiction', 'Business & Economics'),
    'outdoor recreation': ('Travel & Adventure', 'Outdoors'),
    'painting, modern': ('Arts & Entertainment', 'Visual Arts'),
    'paranormal romance stories': ('Special Topics', 'Fantasy & Paranormal'),
    'paris': ('Travel & Adventure', 'Destination'),
    'performing arts': ('Arts & Entertainment', 'Performing Arts'),
    'pets': ('Lifestyle & Home', 'Pets'),
    'philosophy': ('Non-Fiction', 'Philosophy'),
    'photography': ('Arts & Entertainment', 'Visual Arts'),
    'poetry': ('Literature & Fiction', 'Poetry'),
    'political science': ('Non-Fiction', 'Law & Politics'),
    'presidents': ('Non-Fiction', 'Biography & Memoir'),
    'project management': ('Non-Fiction', 'Business & Economics'),
    'psychology': ('Non-Fiction', 'Self-Help & Psychology'),
    'putting (golf)': ('Special Topics', 'Sports & Recreation'),
    'rabbits': ('Non-Fiction', 'Science & Nature'),
    'reference': ('Special Topics', 'Reference'),
    'religion': ('Non-Fiction', 'Religion & Spirituality'),
    'restaurant management': ('Non-Fiction', 'Business & Economics'),
    'rock musicians': ('Non-Fiction', 'Biography & Memoir'),
    'salvation': ('Non-Fiction', 'Religion & Spirituality'),
    'sap r/3': ('Non-Fiction', 'Technology & Engineering'),
    'science': ('Non-Fiction', 'Science & Nature'),
    'second advent': ('Non-Fiction', 'Religion & Spirituality'),
    'self-confidence': ('Non-Fiction', 'Self-Help & Psychology'),
    'self-help': ('Non-Fiction', 'Self-Help & Psychology'),
    'sex instruction for men': ('Non-Fiction', 'Health & Fitness'),
    'silhouettes': ('Arts & Entertainment', 'Visual Arts'),
    'simonov carbine': ('Special Topics', 'Guns'),
    'sinclair, paul (fictitious character)': ('Literature & Fiction', 'Fiction'),
    'social science': ('Non-Fiction', 'Social Science'),
    'spiritual life': ('Non-Fiction', 'Religion & Spirituality'),
    'sports & recreation': ('Special Topics', 'Sports & Recreation'),
    'st. albans (england)': ('Travel & Adventure', 'Destination'),
    'study aids': ('Special Topics', 'Reference'),
    'sunflowers': ('Non-Fiction', 'Science & Nature'),
    'teachers': ('Non-Fiction', 'Education'),
    'technology & engineering': ('Non-Fiction', 'Technology & Engineering'),
    'transportation': ('Lifestyle & Home', 'Transportation'),
    'travel': ('Travel & Adventure', 'Travel'),
    'true crime': ('Literature & Fiction', 'Mystery & Crime'),
    'turning (lathe work)': ('Arts & Entertainment', 'Crafts & Hobbies'),
    'twi language': ('Special Topics', 'Language & Linguistics'),
    'united states': ('Travel & Adventure', 'Destination'),
    'war stories': ('Literature & Fiction', 'Fiction'),
    'werewolves': ('Special Topics', 'Fantasy & Paranormal'),
    'world war, 1914-1918': ('Non-Fiction', 'History'),
    'world war, 1939-1945': ('Non-Fiction', 'History'),
    'young adult fiction': ("Children's & Young Adult", 'Young Adult Fiction'),
    'young adult nonfiction': ("Children's & Young Adult", 'Young Adult Non-Fiction')
}